version: "3.8"

services:
  taishan-admin:
    build: .
    image: taishan-admin:alpine
    container_name: web-admin
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "9000:80"
    environment:
      - API_SERVER=http://0.0.0.0:8000
